/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Controladores.UtilidadesPantalla;
import Modelos.Usuario;
import javax.help.HelpBroker;
import javax.help.HelpSet;

import java.awt.Font;
import java.awt.Color;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author prueba
 */
public class Formulario extends javax.swing.JDialog {

    /**
     * Creates new form Formulario
     */
    public Formulario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        IniciarOtrosComponentes();
        initPlaceHolder();
        UtilidadesPantalla.resolucionPantallaExterna(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        btnAyuda = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblTituloCuenta = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        lblPass = new javax.swing.JLabel();
        txtPass = new javax.swing.JPasswordField();
        txtPassConfirm = new javax.swing.JPasswordField();
        lblCorreoRecuperacion = new javax.swing.JLabel();
        txtUser2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtEmail2 = new javax.swing.JTextField();
        lblCheck = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblTituloPersonal = new javax.swing.JLabel();
        cbxSexo = new javax.swing.JComboBox<>();
        lblSexo = new javax.swing.JLabel();
        lblFechaNacimiento = new javax.swing.JLabel();
        cbxDia = new javax.swing.JComboBox<>();
        cbxMes = new javax.swing.JComboBox<>();
        lblTlf = new javax.swing.JLabel();
        txtTlf = new javax.swing.JTextField();
        lblUbicacion = new javax.swing.JLabel();
        cbxPaises = new javax.swing.JComboBox<>();
        txtNombre = new javax.swing.JTextField();
        txtApellidos = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        cbxAño = new javax.swing.JComboBox<>();
        lblPais = new javax.swing.JLabel();
        cbxComunidad = new javax.swing.JComboBox<>();
        txtComunidad = new javax.swing.JTextField();
        cbxProvincia = new javax.swing.JComboBox<>();
        txtProvincia = new javax.swing.JTextField();
        cbxCiudad = new javax.swing.JComboBox<>();
        txtCiudad = new javax.swing.JTextField();
        lblUbicacion1 = new javax.swing.JLabel();
        txtDomicilio = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        check = new javax.swing.JCheckBox();
        checkAdmin = new javax.swing.JCheckBox();
        btnCancelar = new btn.btn();
        btnAceptar = new btn.btn();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Create account");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(1360, 762));
        setMinimumSize(new java.awt.Dimension(1360, 762));
        setPreferredSize(new java.awt.Dimension(1360, 762));
        setResizable(false);
        setSize(new java.awt.Dimension(1360, 762));

        jPanel4.setBackground(new java.awt.Color(204, 255, 204));
        jPanel4.setMaximumSize(new java.awt.Dimension(1366, 768));
        jPanel4.setMinimumSize(new java.awt.Dimension(1360, 762));
        jPanel4.setPreferredSize(new java.awt.Dimension(1360, 762));
        jPanel4.setRequestFocusEnabled(false);

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));

        lblTitulo.setFont(new java.awt.Font("Agency FB", 1, 48)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(0, 0, 0));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Crea tu cuenta de Usuario");

        btnAyuda.setBackground(new java.awt.Color(255, 255, 204));
        btnAyuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ayuda .png"))); // NOI18N
        btnAyuda.setText("Ayuda");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAyuda)
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 1330, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(24, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 66, Short.MAX_VALUE)
                .addComponent(btnAyuda))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lblTitulo)
                    .addContainerGap(34, Short.MAX_VALUE)))
        );

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setPreferredSize(new java.awt.Dimension(400, 450));

        lblTituloCuenta.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        lblTituloCuenta.setForeground(new java.awt.Color(0, 0, 0));
        lblTituloCuenta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloCuenta.setText("Cuenta");

        lblUsuario.setFont(new java.awt.Font("Laksaman", 0, 12)); // NOI18N
        lblUsuario.setText("Usuario:");

        lblPass.setFont(new java.awt.Font("Laksaman", 0, 12)); // NOI18N
        lblPass.setText("Contraseña:");

        txtPassConfirm.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPassConfirmFocusLost(evt);
            }
        });
        txtPassConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPassConfirmActionPerformed(evt);
            }
        });

        lblCorreoRecuperacion.setFont(new java.awt.Font("Laksaman", 0, 12)); // NOI18N
        lblCorreoRecuperacion.setText("Correo de recuperacion:");
        lblCorreoRecuperacion.setToolTipText("");

        jLabel7.setFont(new java.awt.Font("Laksaman", 0, 14)); // NOI18N
        jLabel7.setText("@");

        txtEmail2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEmail2FocusLost(evt);
            }
        });

        lblCheck.setFont(new java.awt.Font("Laksaman", 1, 12)); // NOI18N
        lblCheck.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblUsuario))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPass)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtPassConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtUser2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtEmail2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblCorreoRecuperacion))
                        .addGap(82, 82, 82)))
                .addContainerGap())
            .addComponent(lblTituloCuenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(lblTituloCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(lblCorreoRecuperacion, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtUser2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEmail2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(lblPass, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtPassConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(50, 50, 50)
                .addComponent(lblCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(204, 255, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblTituloPersonal.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        lblTituloPersonal.setForeground(new java.awt.Color(0, 0, 0));
        lblTituloPersonal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloPersonal.setText("Datos personales");
        lblTituloPersonal.setToolTipText("");

        cbxSexo.setFont(new java.awt.Font("Laksaman", 0, 14)); // NOI18N
        cbxSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona el sexo", "Mujer", "Hombre", "Otro", "No quiero decirlo" }));
        cbxSexo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cbxSexoFocusGained(evt);
            }
        });

        lblSexo.setFont(new java.awt.Font("Laksaman", 0, 12)); // NOI18N
        lblSexo.setText("Sexo:");

        lblFechaNacimiento.setFont(new java.awt.Font("Laksaman", 0, 12)); // NOI18N
        lblFechaNacimiento.setText("Fecha de Nacimiento:");

        cbxDia.setFont(new java.awt.Font("Laksaman", 0, 14)); // NOI18N
        cbxDia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dia" }));
        cbxDia.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cbxDiaFocusGained(evt);
            }
        });

        cbxMes.setFont(new java.awt.Font("Laksaman", 0, 14)); // NOI18N
        cbxMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mes", "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));
        cbxMes.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cbxMesFocusGained(evt);
            }
        });

        lblTlf.setFont(new java.awt.Font("Laksaman", 0, 12)); // NOI18N
        lblTlf.setText("Telefono:");

        txtTlf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                sinLetrasKeyTyped(evt);
            }
        });

        lblUbicacion.setFont(new java.awt.Font("Laksaman", 0, 12)); // NOI18N
        lblUbicacion.setText("Ubicación:");

        cbxPaises.setFont(new java.awt.Font("Laksaman", 0, 14)); // NOI18N
        cbxPaises.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cbxPaisesFocusLost(evt);
            }
        });
        cbxPaises.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxPaisesActionPerformed(evt);
            }
        });

        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                sinNumerosKeyTyped(evt);
            }
        });

        txtApellidos.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtApellidosFocusLost(evt);
            }
        });

        lblNombre.setFont(new java.awt.Font("Laksaman", 0, 12)); // NOI18N
        lblNombre.setText("Nombre:");

        cbxAño.setFont(new java.awt.Font("Laksaman", 0, 14)); // NOI18N
        cbxAño.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Año" }));
        cbxAño.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cbxAñoFocusGained(evt);
            }
        });

        cbxComunidad.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxComunidadItemStateChanged(evt);
            }
        });

        cbxProvincia.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxProvinciaItemStateChanged(evt);
            }
        });

        cbxCiudad.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxCiudadItemStateChanged(evt);
            }
        });

        lblUbicacion1.setFont(new java.awt.Font("Laksaman", 0, 12)); // NOI18N
        lblUbicacion1.setText("Domicilio:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTituloPersonal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lblNombre))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblSexo)
                                    .addComponent(cbxSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblFechaNacimiento)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(cbxAño, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(cbxMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(cbxDia, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(31, 31, 31)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTlf, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblTlf)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtProvincia, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtComunidad, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                    .addComponent(txtCiudad))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbxComunidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbxProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbxCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(cbxPaises, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblPais, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(lblUbicacion)
                                .addGap(142, 142, 142)
                                .addComponent(lblUbicacion1)))
                        .addGap(0, 140, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(lblTituloPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTlf, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxDia, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxMes, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxAño, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTlf, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUbicacion1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPais, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxPaises, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtComunidad, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxComunidad, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtNombre.getAccessibleContext().setAccessibleName("Nombre");

        jPanel5.setBackground(new java.awt.Color(204, 255, 204));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        check.setBackground(new java.awt.Color(255, 255, 204));
        check.setFont(new java.awt.Font("Laksaman", 0, 14)); // NOI18N
        check.setText("Acepto los términos y condiciones al crear mi usuario.");

        checkAdmin.setBackground(new java.awt.Color(255, 255, 204));
        checkAdmin.setFont(new java.awt.Font("Laksaman", 0, 14)); // NOI18N
        checkAdmin.setText("Pulsa para hacer Administrador.");

        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCancelarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnCancelarMouseReleased(evt);
            }
        });

        btnAceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnAceptarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnAceptarMouseReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Requisitos");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 322, Short.MAX_VALUE)
                        .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(check, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(checkAdmin))
                        .addGap(49, 49, 49)))
                .addGap(40, 40, 40))
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(210, 210, 210)
                .addComponent(check)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkAdmin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAceptar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(83, 83, 83))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1360, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleName("Nombre");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMousePressed
        // TODO add your handling code here:
        btnCancelar.pulse();

    }//GEN-LAST:event_btnCancelarMousePressed

    private void btnCancelarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseReleased
        // TODO add your handling code here:
        btnCancelar.pulse();
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelarMouseReleased

    private void btnAceptarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAceptarMousePressed
        // TODO add your handling code here:

        btnAceptar.pulse();
        if (check.isSelected()) {

        } else {
            lblCheck.setText("Tienes que aceptar los terminos de uso");
        }

    }//GEN-LAST:event_btnAceptarMousePressed
    private String sacarMes() {
        String meses=(String) cbxMes.getSelectedItem();
        String mes=null;
        switch (meses) {
            case "Enero":
                mes="01";
                break;
            case "Febrero":
                mes="02";
                break;
            case "Marzo":
                mes="03";
                break;
            case "Abril": 
                mes="04";
                break;
            case "Mayo":
                mes="05";
                break;
            case "Junio":
                mes="06";
                break;
            case "Julio":
                mes="07";
                break;
            case "Agosto":
                mes="08";
                break;
            case "Septiembre":
                mes="09";
                break;
            case "Octubre":
                mes="10";
                break;
            case "Noviembre":
                mes="11";
                break;
            case "Diciembre":
                mes="12";
                break;
        }
        return mes;
    }
    private void btnAceptarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAceptarMouseReleased
        // TODO add your handling code here:
        if (check.isSelected()) {
            boolean admin = true;
            btnAceptar.pulse();
            if (checkAdmin.isSelected()) {
                admin = false;
            }
            
            String pass = new String(txtPass.getPassword());
            LocalDate fechaNac = LocalDate.parse(cbxAño.getSelectedItem() + "-" + sacarMes() + "-" + cbxDia.getSelectedItem(), DateTimeFormatter.ISO_LOCAL_DATE);
            user = new Usuario(0,
                    txtUser.getText(),
                    pass,
                    admin,
                    txtUser2.getText() + "@" + txtEmail2.getText(),
                    txtNombre.getText(),
                    txtApellidos.getText(),
                    Integer.parseInt(txtTlf.getText()),
                    (String) cbxSexo.getSelectedItem(),
                    fechaNac,
                    (String) cbxPaises.getSelectedItem(),
                    (String) txtComunidad.getText(),
                    (String) txtProvincia.getText(),
                    (String) txtCiudad.getText(),
                    txtDomicilio.getText()
            );
            this.setVisible(false);
        } else {
            JOptionPane.showMessageDialog(this, "Tienes que aceptar los terminos y condiciones", "IMPORTANTE", HEIGHT);
        }
    }//GEN-LAST:event_btnAceptarMouseReleased

    private void txtPassConfirmFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPassConfirmFocusLost
        // TODO add your handling code here:
        String pass = new String(txtPass.getPassword());
        String pass2 = new String(txtPassConfirm.getPassword());

        if (pass.equals(pass2)) {
            if (kik) {
                lblPass.setText("Contraseña: " + " Correcto");
                lblPass.setForeground(Color.black);
                kik = false;
            }
        } else {

            lblPass.setText("Las contraseñas no coinciden");
            lblPass.setForeground(Color.red);

        }
    }//GEN-LAST:event_txtPassConfirmFocusLost

    private void txtEmail2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmail2FocusLost
        // TODO add your handling code here:
        if (txtEmail2.getText().isEmpty()) {
            lblCorreoRecuperacion.setForeground(Color.red);
        }
    }//GEN-LAST:event_txtEmail2FocusLost

    private void cbxComunidadItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxComunidadItemStateChanged
        cbxProvincia.setVisible(true);
        BufferedReader br = null;
        File archivo;
        try {
            if (cbxComunidad.getSelectedItem().equals("Andalucia")) {
                cbxProvincia.removeAllItems();
                archivo = new File("lib" + File.separator + "DocumentosTexto" + File.separator + "Provincias" + File.separator + "Andalucia.txt");
                br = new BufferedReader(new FileReader(archivo));
                String lineaLeida;
                lineaLeida = br.readLine();
                while (lineaLeida != null) {
                    cbxProvincia.addItem(lineaLeida);
                    lineaLeida = br.readLine();
                }
                br.close();
            }
            if (cbxComunidad.getSelectedItem().equals("Aragon")) {
                cbxProvincia.removeAllItems();
                archivo = new File("lib" + File.separator + "DocumentosTexto" + File.separator + "Provincias" + File.separator + "Aragon.txt");
                br = new BufferedReader(new FileReader(archivo));
                String lineaLeida;
                lineaLeida = br.readLine();
                while (lineaLeida != null) {
                    cbxProvincia.addItem(lineaLeida);
                    lineaLeida = br.readLine();
                }
                br.close();
            }
            if (cbxComunidad.getSelectedItem().equals("Asturias")) {
                cbxProvincia.removeAllItems();
                cbxProvincia.setVisible(false);
                cbxProvincia.addItem("Asturias");
            }
            if (cbxComunidad.getSelectedItem().equals("Baleares")) {
                cbxProvincia.removeAllItems();
                cbxProvincia.setVisible(false);
                cbxProvincia.addItem("Baleares");
            }
            if (cbxComunidad.getSelectedItem().equals("Canarias")) {
                cbxProvincia.removeAllItems();
                archivo = new File("lib" + File.separator + "DocumentosTexto" + File.separator + "Provincias" + File.separator + "Canarias.txt");
                br = new BufferedReader(new FileReader(archivo));
                String lineaLeida;
                lineaLeida = br.readLine();
                while (lineaLeida != null) {
                    cbxProvincia.addItem(lineaLeida);
                    lineaLeida = br.readLine();
                }
                br.close();
            }
            if (cbxComunidad.getSelectedItem().equals("Cantabria")) {
                cbxProvincia.removeAllItems();
                cbxProvincia.setVisible(false);
            }
            if (cbxComunidad.getSelectedItem().equals("Castilla la Mancha")) {
                cbxProvincia.removeAllItems();
                archivo = new File("lib" + File.separator + "DocumentosTexto" + File.separator + "Provincias" + File.separator + "CastillaLaMancha.txt");
                br = new BufferedReader(new FileReader(archivo));
                String lineaLeida;
                lineaLeida = br.readLine();
                while (lineaLeida != null) {
                    cbxProvincia.addItem(lineaLeida);
                    lineaLeida = br.readLine();
                }
                br.close();
            }
            if (cbxComunidad.getSelectedItem().equals("Castilla Leon")) {
                cbxProvincia.removeAllItems();
                archivo = new File("lib" + File.separator + "DocumentosTexto" + File.separator + "Provincias" + File.separator + "CastillaLeon.txt");
                br = new BufferedReader(new FileReader(archivo));
                String lineaLeida;
                lineaLeida = br.readLine();
                while (lineaLeida != null) {
                    cbxProvincia.addItem(lineaLeida);
                    lineaLeida = br.readLine();
                }
                br.close();
            }
            if (cbxComunidad.getSelectedItem().equals("Cataluna")) {
                cbxProvincia.removeAllItems();
                archivo = new File("lib" + File.separator + "DocumentosTexto" + File.separator + "Provincias" + File.separator + "Cataluna.txt");
                br = new BufferedReader(new FileReader(archivo));
                String lineaLeida;
                lineaLeida = br.readLine();
                while (lineaLeida != null) {
                    cbxProvincia.addItem(lineaLeida);
                    lineaLeida = br.readLine();
                }
                br.close();
            }
            if (cbxComunidad.getSelectedItem().equals("Extremadura")) {
                cbxProvincia.removeAllItems();
                archivo = new File("lib" + File.separator + "DocumentosTexto" + File.separator + "Provincias" + File.separator + "Extremadura.txt");
                br = new BufferedReader(new FileReader(archivo));
                String lineaLeida;
                lineaLeida = br.readLine();
                while (lineaLeida != null) {
                    cbxProvincia.addItem(lineaLeida);
                    lineaLeida = br.readLine();
                }
                br.close();
            }
            if (cbxComunidad.getSelectedItem().equals("Galicia")) {
                cbxProvincia.removeAllItems();
                archivo = new File("lib" + File.separator + "DocumentosTexto" + File.separator + "Provincias" + File.separator + "Galicia.txt");
                br = new BufferedReader(new FileReader(archivo));
                String lineaLeida;
                lineaLeida = br.readLine();
                while (lineaLeida != null) {
                    cbxProvincia.addItem(lineaLeida);
                    lineaLeida = br.readLine();
                }
                br.close();
            }
            if (cbxComunidad.getSelectedItem().equals("La Rioja")) {
                cbxProvincia.removeAllItems();
                cbxProvincia.setVisible(false);
                cbxProvincia.addItem("La Rioja");
            }
            if (cbxComunidad.getSelectedItem().equals("Madrid")) {
                cbxProvincia.removeAllItems();
                cbxProvincia.setVisible(false);
                cbxProvincia.addItem("Madrid");
            }
            if (cbxComunidad.getSelectedItem().equals("Murcia")) {
                cbxProvincia.removeAllItems();
                cbxProvincia.setVisible(false);
                cbxProvincia.addItem("Murcia");
            }
            if (cbxComunidad.getSelectedItem().equals("Navarra")) {
                cbxProvincia.removeAllItems();
                cbxProvincia.setVisible(false);
                cbxProvincia.addItem("Navarra");
            }
            if (cbxComunidad.getSelectedItem().equals("Pais Vasco")) {
                cbxProvincia.removeAllItems();
                archivo = new File("lib" + File.separator + "DocumentosTexto" + File.separator + "Provincias" + File.separator + "PaisVasco.txt");
                br = new BufferedReader(new FileReader(archivo));
                String lineaLeida;
                lineaLeida = br.readLine();
                while (lineaLeida != null) {
                    cbxProvincia.addItem(lineaLeida);
                    lineaLeida = br.readLine();
                }
                br.close();
            }
            if (cbxComunidad.getSelectedItem().equals("Valencia")) {
                cbxProvincia.removeAllItems();
                archivo = new File("lib" + File.separator + "DocumentosTexto" + File.separator + "Provincias" + File.separator + "Valencia.txt");
                br = new BufferedReader(new FileReader(archivo));
                String lineaLeida;
                lineaLeida = br.readLine();
                while (lineaLeida != null) {
                    cbxProvincia.addItem(lineaLeida);
                    lineaLeida = br.readLine();
                }
                br.close();
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Formulario.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Formulario.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtComunidad.setText((String) cbxComunidad.getSelectedItem());
    }//GEN-LAST:event_cbxComunidadItemStateChanged

    private void cbxAñoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbxAñoFocusGained

        if (cbxAño.getSelectedItem().equals("Año")) {
            cbxAño.removeItemAt(0);
        }
    }//GEN-LAST:event_cbxAñoFocusGained

    private void txtApellidosFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtApellidosFocusLost
        // TODO add your handling code here:
        if (txtNombre.getText().isEmpty() && txtApellidos.getText().isEmpty()) {
            lblNombre.setForeground(Color.red);
        }
    }//GEN-LAST:event_txtApellidosFocusLost

    private void sinNumerosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sinNumerosKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if ((c < 'a' || c > 'z') && (c < 'A' || c > 'Z') && (c < 'ñ' || c > 'ñ') && (c < 'Ñ' || c > 'Ñ')
                && (c < ' ' || c > ' ')) {
            evt.consume();
        }
    }//GEN-LAST:event_sinNumerosKeyTyped

    private void cbxPaisesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxPaisesActionPerformed
        String pais = (String) cbxPaises.getSelectedItem();
        int tamaño = pais.length();
        String pais3 = pais.substring(tamaño - 3, tamaño - 1);
        pais3 = pais3.toLowerCase();
        pais = "lib" + File.separator + "BanderasPNG" + File.separator + "" + pais3 + ".png";
        //JOptionPane.showMessageDialog(this, pais);
        ImageIcon img = new ImageIcon(pais);
        //Icon icono=new ImageIcon(img.getImage().getScaledInstance(lblPais.getWidth(),lblPais.getHeight(), Image.SCALE_DEFAULT)); 
        lblPais.setIcon(img);
        mostrarComunidades();
    }//GEN-LAST:event_cbxPaisesActionPerformed

    private void cbxPaisesFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbxPaisesFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxPaisesFocusLost

    private void sinLetrasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sinLetrasKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if ((c < '0' || c > '9')) {
            evt.consume();
        }
    }//GEN-LAST:event_sinLetrasKeyTyped

    private void cbxMesFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbxMesFocusGained
        // TODO add your handling code here:
        if (cbxMes.getSelectedItem().equals("Mes")) {
            cbxMes.removeItemAt(0);
        }
    }//GEN-LAST:event_cbxMesFocusGained

    private void cbxDiaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbxDiaFocusGained
        // TODO add your handling code here:
        if (cbxDia.getSelectedItem().equals("Dia")) {
            cbxDia.removeItemAt(0);
        }
        switch (cbxMes.getSelectedItem().toString()) {
            case "Enero":
                dias = 31;
                break;
            case "Febrero":
                dias = 28;
                break;
            case "Marzo":
                dias = 31;
                break;
            case "Abril":
                dias = 30;
                break;
            case "Mayo":
                dias = 31;
                break;
            case "Junio":
                dias = 30;
                break;
            case "Julio":
                dias = 31;
                break;
            case "Agosto":
                dias = 31;
                break;
            case "Septiembre":
                dias = 30;
                break;
            case "Octubre":
                dias = 31;
                break;
            case "Noviembre":
                dias = 30;
                break;
            case "Diciembre":
                dias = 31;
                break;
        }
        cbxDia.removeAllItems();
        for (int i = 1; i <= dias; i++) {
            if(i<10){
            cbxDia.addItem("0" + i);
            }else{
            cbxDia.addItem("" + i);
            }
        }
    }//GEN-LAST:event_cbxDiaFocusGained

    private void cbxSexoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbxSexoFocusGained
        // TODO add your handling code here:
        if (cbxSexo.getSelectedItem().equals("Selecciona el sexo")) {
            cbxSexo.removeItemAt(0);
        }
    }//GEN-LAST:event_cbxSexoFocusGained

    private void cbxProvinciaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxProvinciaItemStateChanged

        cbxCiudad.setVisible(true);
        BufferedReader br = null;
        File archivo = null;
        try {
            String provincia = cbxProvincia.getSelectedItem().toString();

            cbxCiudad.removeAllItems();
            archivo = new File("lib" + File.separator + "DocumentosTexto" + File.separator + "pueblos" + provincia + ".txt");
            br = new BufferedReader(new FileReader(archivo));
            String lineaLeida;
            lineaLeida = br.readLine();
            while (lineaLeida != null) {
                cbxCiudad.addItem(lineaLeida);
                lineaLeida = br.readLine();
            }
            br.close();

        } catch (FileNotFoundException ex) {
            Logger.getLogger(Formulario.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Formulario.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NullPointerException e) {

        }
        txtProvincia.setText((String) cbxProvincia.getSelectedItem());
    }//GEN-LAST:event_cbxProvinciaItemStateChanged

    private void cbxCiudadItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxCiudadItemStateChanged
        // TODO add your handling code here:
        txtCiudad.setText((String) cbxCiudad.getSelectedItem());
    }//GEN-LAST:event_cbxCiudadItemStateChanged

    private void txtPassConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPassConfirmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPassConfirmActionPerformed
    void setUsuario(Usuario usu) {
    }

    public Usuario getUsuario() {
        return this.user;
    }

    private void mostrarComunidades() {
        if (cbxPaises.getSelectedItem().equals("Spain 	ES ")) {
            txtComunidad.setVisible(false);
            txtProvincia.setVisible(false);
            txtCiudad.setVisible(false);
            cbxComunidad.setVisible(true);
            try {
                BufferedReader br = new BufferedReader(new FileReader(new File("lib" + File.separator + "DocumentosTexto" + File.separator + "Comunidades.txt")));
                try {
                    String linea = br.readLine();
                    while (linea != null) {
                        cbxComunidad.addItem(linea);
                        linea = br.readLine();
                    }
                } catch (ArrayIndexOutOfBoundsException e) {
                    JOptionPane.showMessageDialog(rootPane, e.getMessage());
                } catch (IOException ex) {
                    Logger.getLogger(Formulario.class.getName()).log(Level.SEVERE, null, ex);
                }
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Formulario.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else {
            cbxComunidad.setVisible(false);
            cbxCiudad.setVisible(false);
            cbxProvincia.setVisible(false);
            txtComunidad.setVisible(true);
            txtProvincia.setVisible(true);
            txtCiudad.setVisible(true);
        }
    }

    private void ponLaAyuda() {
        try {
            // Carga el fichero de ayuda
            java.net.URL hsURL = UtilidadesPantalla.obtenerUrlAyuda();
            HelpSet helpset = new HelpSet(getClass().getClassLoader(), hsURL);
            HelpBroker hb = helpset.createHelpBroker();

            // Pone ayuda a item de menu al pulsarlo y a F1 en ventana
            hb.enableHelpOnButton(btnAyuda, "formulario", helpset);
            hb.enableHelpKey(getRootPane(), "formulario", helpset);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Formulario dialog = new Formulario(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    ArrayList paises;
    ArrayList abreviaturas;
    Usuario user=null;
    private int dias = 31;
    boolean kik = true;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private btn.btn btnAceptar;
    private javax.swing.JButton btnAyuda;
    private btn.btn btnCancelar;
    private javax.swing.JComboBox<String> cbxAño;
    private javax.swing.JComboBox<String> cbxCiudad;
    private javax.swing.JComboBox<String> cbxComunidad;
    private javax.swing.JComboBox<String> cbxDia;
    private javax.swing.JComboBox<String> cbxMes;
    private javax.swing.JComboBox<String> cbxPaises;
    private javax.swing.JComboBox<String> cbxProvincia;
    private javax.swing.JComboBox<String> cbxSexo;
    private javax.swing.JCheckBox check;
    private javax.swing.JCheckBox checkAdmin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lblCheck;
    private javax.swing.JLabel lblCorreoRecuperacion;
    private javax.swing.JLabel lblFechaNacimiento;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPais;
    private javax.swing.JLabel lblPass;
    private javax.swing.JLabel lblSexo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTituloCuenta;
    private javax.swing.JLabel lblTituloPersonal;
    private javax.swing.JLabel lblTlf;
    private javax.swing.JLabel lblUbicacion;
    private javax.swing.JLabel lblUbicacion1;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtCiudad;
    private javax.swing.JTextField txtComunidad;
    private javax.swing.JTextField txtDomicilio;
    private javax.swing.JTextField txtEmail2;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JPasswordField txtPassConfirm;
    private javax.swing.JTextField txtProvincia;
    private javax.swing.JTextField txtTlf;
    private javax.swing.JTextField txtUser;
    private javax.swing.JTextField txtUser2;
    // End of variables declaration//GEN-END:variables

    private void initPlaceHolder() {
        //Nombre
        TextPrompt placeholder = new TextPrompt("Nombre", txtNombre);
        placeholder.changeAlpha(0.75f);
        placeholder.changeStyle(Font.ITALIC);
        placeholder = new TextPrompt("Apellidos", txtApellidos);
        placeholder.changeAlpha(0.75f);
        placeholder.changeStyle(Font.ITALIC);
        //Usuario
        placeholder = new TextPrompt("Ejemplo", txtUser);
        placeholder.changeAlpha(0.75f);
        placeholder.changeStyle(Font.ITALIC);
        //Contraseña
        placeholder = new TextPrompt("Contraseña", txtPass);
        placeholder.changeAlpha(0.75f);
        placeholder.changeStyle(Font.ITALIC);
        placeholder = new TextPrompt("Confirmar Contraseña", txtPassConfirm);
        placeholder.changeAlpha(0.75f);
        placeholder.changeStyle(Font.ITALIC);
        //Correo
        placeholder = new TextPrompt("Ejemplo", txtUser2);
        placeholder.changeAlpha(0.75f);
        placeholder.changeStyle(Font.ITALIC);
        placeholder = new TextPrompt("Ejemplo.com", txtEmail2);
        placeholder.changeAlpha(0.75f);
        placeholder.changeStyle(Font.ITALIC);
        //Datos Personales
        placeholder = new TextPrompt("Comunidad Autonoma", txtComunidad);
        placeholder.changeAlpha(0.75f);
        placeholder.changeStyle(Font.ITALIC);
        placeholder = new TextPrompt("Provincia", txtProvincia);
        placeholder.changeAlpha(0.75f);
        placeholder.changeStyle(Font.ITALIC);
        placeholder = new TextPrompt("Ciudad", txtCiudad);
        placeholder.changeAlpha(0.75f);
        placeholder.changeStyle(Font.ITALIC);
        placeholder = new TextPrompt("C/animus", txtDomicilio);
        placeholder.changeAlpha(0.75f);
        placeholder.changeStyle(Font.ITALIC);
        placeholder = new TextPrompt("669...", txtTlf);
        placeholder.changeAlpha(0.75f);
        placeholder.changeStyle(Font.ITALIC);

    }

    private void IniciarOtrosComponentes() {
        ponLaAyuda();
        cbxComunidad.setVisible(false);
        cbxCiudad.setVisible(false);
        cbxProvincia.setVisible(false);
        ImageIcon img = new ImageIcon("lib" + File.separator + "BanderasPNG" + File.separator + "es.png");
        //Icon icono=new ImageIcon(img.getImage().getScaledInstance(lblPais.getWidth(),lblPais.getHeight(), Image.SCALE_DEFAULT)); 
        lblPais.setIcon(img);
        paises = new ArrayList();
        abreviaturas = new ArrayList();
        cbxDia.removeAllItems();
        cbxDia.addItem("Dia");
        for (int i = 1; i <= dias; i++) {
            if(i<10){
            cbxDia.addItem("0" + i);
            }else{
            cbxDia.addItem("" + i);
            }
        }
        for (int i = 2020; i >= 1900; i--) {
            cbxAño.addItem("" + i);
        }
        btnCancelar.word("Cancelar");
        btnAceptar.word("Confirmar");

        /*try {
            BufferedReader br =new BufferedReader(new FileReader(new File("Paises.txt")));
            try {
                String linea=br.readLine();
                while(linea!=null){
                    paises(linea);
                    linea=br.readLine();
                }
            } catch (IOException ex) {
                Logger.getLogger(Formulario.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Formulario.class.getName()).log(Level.SEVERE, null, ex);
        }*/
        try {
            BufferedReader br = new BufferedReader(new FileReader(new File("lib" + File.separator + "DocumentosTexto" + File.separator + "Abre.txt")));
            try {
                String linea = br.readLine();
                while (linea != null) {
                    String pais = linea;
                    paises.add(pais);
                    linea = br.readLine();
                }
            } catch (ArrayIndexOutOfBoundsException e) {
                JOptionPane.showMessageDialog(rootPane, e.getMessage());
            } catch (IOException ex) {
                Logger.getLogger(Formulario.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Formulario.class.getName()).log(Level.SEVERE, null, ex);
        }
        for (int i = 0; i < paises.size(); i++) {
            cbxPaises.addItem((String) paises.get(i));
        }

    }

}
