/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Controladores.GestionAlquiler;
import Controladores.GestionPistas;
import Controladores.UtilidadesPantalla;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Modelos.Alquiler;
import Modelos.Pista;
import Modelos.Usuario;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import javax.help.HelpBroker;
import javax.help.HelpSet;

/**
 *
 * @author DAM2
 */
public class ReservarPista extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public ReservarPista(Usuario usu) {
        try {
            this.usuarioReservar = usu;
            initComponents();
            //Cargamos las listas de las pistas y de los alquileres obtenidos
            alquileres = GA.gestionListarAlquileres();
            pistas = GP.gestionListarPistas();
            pistaSeleccionada = pistas.get(0);
            //luego creamos un modelo para cada pista obtenida
            GP.crearPistas();
            //y para terminar rellenamos todas las tablas
            rellenarTablas();
            //iniciarOtrosComponentes();
            ponLaAyuda();
            UtilidadesPantalla.resolucionPantalla(this);
            UtilidadesPantalla.centrarTablas(tblHecha);
            UtilidadesPantalla.centrarTablas(tblReserva);
            txtNombre.setText("Nombre: " + usuarioReservar.getNombre() + " " + usuarioReservar.getApellidos());
        } catch (Exception e) {

        }
    }

    private void rellenarTablas() {
        DefaultTableModel modeloReserva = (DefaultTableModel) tblReserva.getModel();
        DefaultTableModel modeloReservaHecha = (DefaultTableModel) tblHecha.getModel();
        for (int j = 0; j < alquileres.size(); j++) {
            if (alquileres.get(j).p.getNum() == pistaSeleccionada.getNum()) {
                modeloReserva = GP.getModeloReserva(pistaSeleccionada.getNum(), alquileres);
                if (alquileres.get(j).getUsu().getId() == usuarioReservar.getId()) {
                    modeloReservaHecha = GP.getModeloReservaHecha(pistaSeleccionada.getNum(), alquileres);
                }
            }
        }
        tblReserva.setModel(modeloReserva);
        tblHecha.setModel(modeloReservaHecha);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo = new javax.swing.JPanel();
        labelHeader1 = new org.edisoncor.gui.label.LabelHeader();
        jPanel1 = new javax.swing.JPanel();
        btnPista1 = new org.edisoncor.gui.button.ButtonIcon();
        btnPista3 = new org.edisoncor.gui.button.ButtonIcon();
        btnPista2 = new org.edisoncor.gui.button.ButtonIcon();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblReserva = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblHecha = new javax.swing.JTable();
        btnFlechaIzq = new org.edisoncor.gui.button.ButtonIcon();
        btnFlechaDch = new org.edisoncor.gui.button.ButtonIcon();
        txtNombre = new javax.swing.JLabel();
        txtPista = new javax.swing.JLabel();
        txtTusReservas = new javax.swing.JLabel();
        btnAyuda = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 204));
        setMaximumSize(new java.awt.Dimension(1360, 762));
        setMinimumSize(new java.awt.Dimension(1360, 762));
        setPreferredSize(new java.awt.Dimension(1360, 762));
        setResizable(false);
        setSize(new java.awt.Dimension(1360, 762));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelHeader1.setBackground(new java.awt.Color(204, 255, 204));
        labelHeader1.setForeground(new java.awt.Color(0, 102, 0));
        labelHeader1.setText("Reserva tu pista");
        labelHeader1.setColor(new java.awt.Color(204, 255, 204));
        labelHeader1.setColorDeSombra(new java.awt.Color(204, 255, 204));
        labelHeader1.setFont(new java.awt.Font("Agency FB", 1, 48)); // NOI18N

        javax.swing.GroupLayout TituloLayout = new javax.swing.GroupLayout(Titulo);
        Titulo.setLayout(TituloLayout);
        TituloLayout.setHorizontalGroup(
            TituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelHeader1, javax.swing.GroupLayout.DEFAULT_SIZE, 1360, Short.MAX_VALUE)
        );
        TituloLayout.setVerticalGroup(
            TituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TituloLayout.createSequentialGroup()
                .addComponent(labelHeader1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        getContentPane().add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 0, 1360, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnPista1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pistaPadelModularVerde.jpg"))); // NOI18N
        btnPista1.setText("buttonIcon1");
        btnPista1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPista1ActionPerformed(evt);
            }
        });

        btnPista3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pistaPadelModularVerde.jpg"))); // NOI18N
        btnPista3.setText("buttonIcon2");
        btnPista3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPista3ActionPerformed(evt);
            }
        });

        btnPista2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pistaPadelModularVerde.jpg"))); // NOI18N
        btnPista2.setText("buttonIcon3");
        btnPista2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPista2ActionPerformed(evt);
            }
        });

        jLabel1.setText("Pista 1");

        jLabel2.setText("Pista 2");

        jLabel3.setText("Pista 3");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnPista1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPista2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPista3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabel1)
                        .addGap(108, 108, 108)
                        .addComponent(jLabel2)
                        .addGap(108, 108, 108)
                        .addComponent(jLabel3)))
                .addContainerGap(918, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPista3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnPista2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnPista1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 90, 1360, 120));

        tblReserva.setBackground(new java.awt.Color(204, 255, 204));
        tblReserva.setForeground(new java.awt.Color(0, 102, 102));
        tblReserva.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Dia", "Hora Inicio", "Hora Final"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblReserva.setRowHeight(20);
        tblReserva.setSelectionForeground(new java.awt.Color(102, 255, 255));
        jScrollPane1.setViewportView(tblReserva);
        if (tblReserva.getColumnModel().getColumnCount() > 0) {
            tblReserva.getColumnModel().getColumn(0).setResizable(false);
            tblReserva.getColumnModel().getColumn(1).setResizable(false);
            tblReserva.getColumnModel().getColumn(2).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 680, 360));

        tblHecha.setBackground(new java.awt.Color(204, 255, 204));
        tblHecha.setForeground(new java.awt.Color(153, 0, 0));
        tblHecha.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Dia", "Hora Inicio", "Hora Final"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblHecha.setRowHeight(50);
        tblHecha.setSelectionForeground(new java.awt.Color(102, 255, 255));
        jScrollPane2.setViewportView(tblHecha);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 480, 590, 260));

        btnFlechaIzq.setBackground(new java.awt.Color(102, 102, 102));
        btnFlechaIzq.setForeground(new java.awt.Color(102, 102, 102));
        btnFlechaIzq.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/izquierda.png"))); // NOI18N
        btnFlechaIzq.setText("buttonIcon4");
        btnFlechaIzq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFlechaIzqActionPerformed(evt);
            }
        });
        getContentPane().add(btnFlechaIzq, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 620, 40, 30));

        btnFlechaDch.setBackground(new java.awt.Color(102, 102, 102));
        btnFlechaDch.setForeground(new java.awt.Color(102, 102, 102));
        btnFlechaDch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/derecha.png"))); // NOI18N
        btnFlechaDch.setText("buttonIcon4");
        btnFlechaDch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFlechaDchActionPerformed(evt);
            }
        });
        getContentPane().add(btnFlechaDch, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 570, 40, 30));

        txtNombre.setBackground(new java.awt.Color(51, 51, 51));
        txtNombre.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(51, 51, 51));
        txtNombre.setText("Nombre: ");
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 450, -1, -1));

        txtPista.setBackground(new java.awt.Color(51, 51, 51));
        txtPista.setFont(new java.awt.Font("Agency FB", 1, 48)); // NOI18N
        txtPista.setForeground(new java.awt.Color(51, 51, 51));
        txtPista.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtPista.setText("Seleccione una pista");
        getContentPane().add(txtPista, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 680, 160));

        txtTusReservas.setBackground(new java.awt.Color(51, 51, 51));
        txtTusReservas.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        txtTusReservas.setForeground(new java.awt.Color(51, 51, 51));
        txtTusReservas.setText("Tus reservas:");
        getContentPane().add(txtTusReservas, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 440, -1, -1));

        btnAyuda.setBackground(new java.awt.Color(255, 255, 204));
        btnAyuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ayuda .png"))); // NOI18N
        btnAyuda.setText("Ayuda");
        getContentPane().add(btnAyuda, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 210, 100, -1));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Fondo.jpg"))); // NOI18N
        Fondo.setMaximumSize(new java.awt.Dimension(1360, 762));
        Fondo.setMinimumSize(new java.awt.Dimension(1360, 762));
        Fondo.setPreferredSize(new java.awt.Dimension(1360, 762));
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPista1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPista1ActionPerformed
        //try {
        tblReserva.setModel(GP.getModeloReserva(1, alquileres));
        for (int j = 0; j < alquileres.size(); j++) {
            if (alquileres.get(j).getUsu().getId() == usuarioReservar.getId()) {
                tblHecha.setModel(GP.getModeloReservaHecha(1, alquileres));
            }
        }

        pistaSeleccionada = pistas.get(0);
        //} catch (Exception e) {
        //}
        txtPista.setText("1ª Pista");
    }//GEN-LAST:event_btnPista1ActionPerformed

    private void btnPista2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPista2ActionPerformed
        //try {
        tblReserva.setModel(GP.getModeloReserva(2, alquileres));
        for (int j = 0; j < alquileres.size(); j++) {
            if (alquileres.get(j).getUsu().getId() == usuarioReservar.getId()) {
                tblHecha.setModel(GP.getModeloReservaHecha(2, alquileres));
            }
        }

        pistaSeleccionada = pistas.get(1);
        //} catch (Exception e) {
        //}
        txtPista.setText("2ª Pista");
    }//GEN-LAST:event_btnPista2ActionPerformed

    private void btnPista3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPista3ActionPerformed
        //try {
        tblReserva.setModel(GP.getModeloReserva(3, alquileres));
        for (int j = 0; j < alquileres.size(); j++) {
            if (alquileres.get(j).getUsu().getId() == usuarioReservar.getId()) {
                tblHecha.setModel(GP.getModeloReservaHecha(3, alquileres));
            }
        }

        pistaSeleccionada = pistas.get(2);
        //} catch (Exception e) {
        //}
        txtPista.setText("3ª Pista");
    }//GEN-LAST:event_btnPista3ActionPerformed

    private void btnFlechaIzqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFlechaIzqActionPerformed
        int resp = JOptionPane.showConfirmDialog(null, "¿Esta seguro de que quiere borrar la pista a esta hora?", "Alquiler", JOptionPane.YES_NO_OPTION);
        if (resp == 0) {

            DefaultTableModel modelo = (DefaultTableModel) tblReserva.getModel();
            DefaultTableModel modelohecha = (DefaultTableModel) tblHecha.getModel();
            int selec = tblHecha.getSelectedRow();
            LocalDate dia = (LocalDate) modelo.getValueAt(selec, 0);
            LocalTime horaInicio = (LocalTime) modelo.getValueAt(selec, 1);
            LocalTime horaFin = (LocalTime) modelo.getValueAt(selec, 2);
            borrarAlquiler(dia, horaInicio, horaFin);
            modelo.addRow(new Object[]{modelo.getValueAt(selec, 0), modelo.getValueAt(selec, 1), modelo.getValueAt(selec, 2)});
            modelohecha.removeRow(selec);
        }
    }//GEN-LAST:event_btnFlechaIzqActionPerformed

    private void btnFlechaDchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFlechaDchActionPerformed

        int resp = JOptionPane.showConfirmDialog(null, "¿Esta seguro de que quiere alquilar la pista a esta hora?", "Alquiler", JOptionPane.YES_NO_OPTION);
        if (resp == 0) {
            DefaultTableModel modelo = (DefaultTableModel) tblReserva.getModel();
            DefaultTableModel modelohecha = (DefaultTableModel) tblHecha.getModel();
            int selec = tblReserva.getSelectedRow();
            LocalDate dia = (LocalDate) modelo.getValueAt(selec, 0);
            LocalTime horaInicio = (LocalTime) modelo.getValueAt(selec, 1);
            LocalTime horaFin = (LocalTime) modelo.getValueAt(selec, 2);
            Alquiler alquiler = new Alquiler(pistaSeleccionada, usuarioReservar, horaInicio, horaFin, dia);
            GA.gestionInsertarAlquiler(alquiler);
            modelohecha.addRow(new Object[]{modelo.getValueAt(selec, 0), modelo.getValueAt(selec, 1), modelo.getValueAt(selec, 2)});
            modelo.removeRow(selec);

        }
    }//GEN-LAST:event_btnFlechaDchActionPerformed

    private void ponLaAyuda() {
        try {
            java.net.URL hsURL = UtilidadesPantalla.obtenerUrlAyuda();
            // Crea el HelpSet y el HelpBroker
            HelpSet helpset = new HelpSet(getClass().getClassLoader(), hsURL);
            HelpBroker hb = helpset.createHelpBroker();

            // Pone ayuda a item de menu al pulsarlo y a F1 en ventana
            hb.enableHelpOnButton(btnAyuda, "reservar", helpset);
            hb.enableHelpKey(getRootPane(), "reservar", helpset);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReservarPista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReservarPista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReservarPista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReservarPista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReservarPista(new Usuario()).setVisible(true);
            }
        });
    }
    ArrayList<Alquiler> alquileres;
    public ArrayList<Pista> pistas;
    GestionPistas GP = new GestionPistas();
    GestionAlquiler GA = new GestionAlquiler();
    Usuario usuarioReservar;
    Pista pistaSeleccionada;
    DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-d");
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JPanel Titulo;
    private javax.swing.JButton btnAyuda;
    private org.edisoncor.gui.button.ButtonIcon btnFlechaDch;
    private org.edisoncor.gui.button.ButtonIcon btnFlechaIzq;
    private org.edisoncor.gui.button.ButtonIcon btnPista1;
    private org.edisoncor.gui.button.ButtonIcon btnPista2;
    private org.edisoncor.gui.button.ButtonIcon btnPista3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private org.edisoncor.gui.label.LabelHeader labelHeader1;
    private javax.swing.JTable tblHecha;
    private javax.swing.JTable tblReserva;
    private javax.swing.JLabel txtNombre;
    private javax.swing.JLabel txtPista;
    private javax.swing.JLabel txtTusReservas;
    // End of variables declaration//GEN-END:variables

    private void borrarAlquiler(LocalDate dia, LocalTime horaInicio, LocalTime horaFin) {
        int id = 0;
        for (int i = 0; i < alquileres.size(); i++) {
            if (alquileres.get(i).getHoraFin().equals(horaFin)
                    && alquileres.get(i).getHoraInicio().equals(horaInicio)
                    && alquileres.get(i).getDia().equals(dia)) {
                id = alquileres.get(i).getId();
            }
        }
        GA.gestionBorrarAlquiler(id);
    }

}
